In [1]:
import pandas as pd
import numpy as np
import pydataset 
from statsmodels.formula.api import ols

In [2]:
mtcars = pydataset.data('mtcars')
fifa22 = pd.read_csv('datasets/players_fifa22.csv')

In [6]:
mtcars.corr() ** 2 # 제곱하면 결정계수, 제곱안하면 상관계수

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
mpg,1.000000,0.726180,0.718343,0.602437,0.463995,0.752833,0.175296,0.440948,0.359799,0.230673,0.303518
cyl,0.726180,1.000000,0.813663,0.692969,0.489913,0.612300,0.349567,0.657416,0.273118,0.242740,0.277717
disp,0.718343,0.813663,1.000000,0.625600,0.504404,0.788508,0.188094,0.504691,0.349549,0.308657,0.156007
hp,0.602437,0.692969,0.625600,1.000000,0.201385,0.433949,0.501580,0.522869,0.059148,0.015802,0.562219
drat,0.463995,0.489913,0.504404,0.201385,1.000000,0.507572,0.008318,0.193845,0.507957,0.489454,0.008243
wt,0.752833,0.612300,0.788508,0.433949,0.507572,1.000000,0.030526,0.307931,0.479550,0.340224,0.182847
qsec,0.175296,0.349567,0.188094,0.501580,0.008318,0.030526,1.000000,0.554333,0.052836,0.045234,0.430663
vs,0.440948,0.657416,0.504691,0.522869,0.193845,0.307931,0.554333,1.000000,0.028340,0.042446,0.324452
am,0.359799,0.273118,0.349549,0.059148,0.507957,0.479550,0.052836,0.028340,1.000000,0.630529,0.003310
gear,0.230673,0.242740,0.308657,0.015802,0.489454,0.340224,0.045234,0.042446,0.630529,1.000000,0.075116
carb,0.303518,0.277717,0.156007,0.562219,0.008243,0.182847,0.430663,0.324452,0.003310,0.075116,1.000000

In [7]:
mod = ols('mpg ~ wt', data = mtcars).fit()

In [8]:
mod

In [9]:
mod.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.753
Model:                            OLS   Adj. R-squared:                  0.745
Method:                 Least Squares   F-statistic:                     91.38
Date:                Wed, 07 Dec 2022   Prob (F-statistic):           1.29e-10
Time:                        18:42:04   Log-Likelihood:                -80.015
No. Observations:                  32   AIC:                             164.0
Df Residuals:                      30   BIC:                             167.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     37.2851      1.878     19.858      0.000      33.450      41.120
wt            -5.3445      0.559     -9.559      0.000      -6.486      -4.203
==============================================================================
Omnibus:                        2.988   Durbin-Watson:                   1.252
Prob(Omnibus):                  0.225   Jarque-Bera (JB):                2.399
Skew:                           0.668   Prob(JB):                        0.301
Kurtosis:                       2.877   Cond. No.                         12.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [10]:
# mpg = 37.2851 -5.3445 * wt

In [11]:
economics = pydataset.data('economics')

In [12]:
economics

           date     pce     pop  psavert  uempmed  unemploy
1    1967-06-30   507.8  198712      9.8      4.5      2944
2    1967-07-31   510.9  198911      9.8      4.7      2945
3    1967-08-31   516.7  199113      9.0      4.6      2958
4    1967-09-30   513.3  199311      9.8      4.9      3143
5    1967-10-31   518.5  199498      9.7      4.7      3066
..          ...     ...     ...      ...      ...       ...
474  2006-11-30  9478.5  301070     -1.1      7.3      6849
475  2006-12-31  9540.3  301296     -0.9      8.1      7017
476  2007-01-31  9610.6  301481     -1.0      8.1      6865
477  2007-02-28  9653.0  301684     -0.7      8.5      6724
478  2007-03-31  9705.0  301913     -1.3      8.7      6801

[478 rows x 6 columns]

In [15]:
mod2 = ols('pce ~ uempmed', data = economics).fit()

In [16]:
mod2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    pce   R-squared:                       0.265
Model:                            OLS   Adj. R-squared:                  0.263
Method:                 Least Squares   F-statistic:                     171.4
Date:                Wed, 07 Dec 2022   Prob (F-statistic):           1.13e-33
Time:                        18:53:45   Log-Likelihood:                -4364.6
No. Observations:                 478   AIC:                             8733.
Df Residuals:                     476   BIC:                             8742.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -2178.0460    457.061     -4.765      0.000   -3076.153   -1279.939
uempmed      818.6734     62.525     13.094      0.000     695.815     941.532
==============================================================================
Omnibus:                       14.932   Durbin-Watson:                   0.027
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               13.629
Skew:                           0.356   Prob(JB):                      0.00110
Kurtosis:                       2.579   Cond. No.                         33.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
# pce = 467.6886 + 0.4554 * unemploy

In [21]:
korea = fifa22.query('Nationality == "Korea Republic"')

In [22]:
korea

,ID,Name,FullName,Age,Height,Weight,PhotoUrl,Nationality,Overall,Potential,...,LMRating,CMRating,RMRating,LWBRating,CDMRating,RWBRating,LBRating,CBRating,RBRating,GKRating
11,200104,H. Son,Heung Min Son,28,183,78,https://cdn.sofifa.com/players/200/104/22_60.png,Korea Republic,89,89,...,89,83,89,71,67,71,67,57,67,22
1200,212260,Hwang Ui Jo,Ui Jo Hwang,28,185,82,https://cdn.sofifa.com/players/212/260/22_60.png,Korea Republic,76,76,...,74,70,74,62,59,62,60,56,60,19
1686,212432,Jo Hyeon Woo,Hyeon Woo Jo,29,189,75,https://cdn.sofifa.com/players/212/432/22_60.png,Korea Republic,75,75,...,31,32,31,29,30,29,30,28,30,75
1837,221671,Lee Jae Sung,Jae Sung Lee,28,180,70,https://cdn.sofifa.com/players/221/671/22_60.png,Korea Republic,75,75,...,75,75,75,69,69,69,67,59,67,18
2079,211005,Jang Hyeon Soo,Hyeon Soo Jang,29,183,83,https://cdn.sofifa.com/players/211/005/22_60.png,Korea Republic,74,74,...,61,66,61,70,74,70,72,74,72,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19095,261075,Kang Jae Woo,Jae Woo Kang,21,179,72,https://cdn.sofifa.com/players/261/075/22_60.png,Korea Republic,50,63,...,52,51,52,52,52,52,52,52,52,19
19171,252196,Yoon Jong Tae,Jong Tae Yoon,23,182,82,https://cdn.sofifa.com/players/252/196/22_60.png,Korea Republic,49,56,...,50,51,50,49,52,49,49,53,49,18
19191,261052,Kang Dong Hyeok,Dong Hyeok Kang,21,184,73,https://cdn.sofifa.com/players/261/052/22_60.png,Korea Republic,49,58,...,52,51,52,50,50,50,50,49,50,17
19232,255553,Kwon Seong Yoon,Seong Yoon Kwon,20,176,69,https://cdn.sofifa.com/players/255/553/22_60.png,Korea Republic,48,61,...,50,45,50,41,38,41,39,35,39,12
19253,260474,Kim Bong Soo,Bong Soo Kim,21,183,78,https://cdn.sofifa.com/players/260/474/22_60.png,Korea Republic,48,57,...,49,50,49,50,52,50,50,51,50,19

In [26]:
mod3 = ols('WageEUR ~ Potential', data = korea).fit()

In [27]:
mod3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                WageEUR   R-squared:                       0.138
Model:                            OLS   Adj. R-squared:                  0.135
Method:                 Least Squares   F-statistic:                     51.46
Date:                Wed, 07 Dec 2022   Prob (F-statistic):           5.07e-12
Time:                        18:57:05   Log-Likelihood:                -3485.1
No. Observations:                 323   AIC:                             6974.
Df Residuals:                     321   BIC:                             6982.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -5.888e+04   8689.422     -6.776      0.000    -7.6e+04   -4.18e+04
Potential    932.7033    130.014      7.174      0.000     676.915    1188.491
==============================================================================
Omnibus:                      680.416   Durbin-Watson:                   0.981
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           767157.213
Skew:                          14.367   Prob(JB):                         0.00
Kurtosis:                     240.016   Cond. No.                         887.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [34]:
korea.columns

Index(['ID', 'Name', 'FullName', 'Age', 'Height', 'Weight', 'PhotoUrl',
       'Nationality', 'Overall', 'Potential', 'Growth', 'TotalStats',
       'BaseStats', 'Positions', 'BestPosition', 'Club', 'ValueEUR', 'WageEUR',
       'ReleaseClause', 'ClubPosition', 'ContractUntil', 'ClubNumber',
       'ClubJoined', 'OnLoad', 'NationalTeam', 'NationalPosition',
       'NationalNumber', 'PreferredFoot', 'IntReputation', 'WeakFoot',
       'SkillMoves', 'AttackingWorkRate', 'DefensiveWorkRate', 'PaceTotal',
       'ShootingTotal', 'PassingTotal', 'DribblingTotal', 'DefendingTotal',
       'PhysicalityTotal', 'Crossing', 'Finishing', 'HeadingAccuracy',
       'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy',
       'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility',
       'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength',
       'LongShots', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle',
       'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'STRating', 'LWRating', 'LFRating', 'CFRating', 'RFRating', 'RWRating',
       'CAMRating', 'LMRating', 'CMRating', 'RMRating', 'LWBRating',
       'CDMRating', 'RWBRating', 'LBRating', 'CBRating', 'RBRating',
       'GKRating'],
      dtype='object')